var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/matrix-assist/sessions/[id]/route.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__1wf9iwn._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/_next-internal_server_app_api_matrix-assist_sessions_[id]_route_actions_1p7w91o.js")
R.m(600383)
module.exports=R.m(600383).exports
