var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai-operations/predictive-maintenance/forecast/route.js")
R.c("server/chunks/[root-of-the-server]__021pslm._.js")
R.c("server/chunks/[root-of-the-server]__1g6ekzg._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/lib_service-calls_index_ts_1pg5y58._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/1jng_app_api_ai-operations_predictive-maintenance_forecast_route_actions_123yyli.js")
R.m(196552)
module.exports=R.m(196552).exports
