var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai-operations/assistant/feedback/route.js")
R.c("server/chunks/_1vmxktw._.js")
R.c("server/chunks/[root-of-the-server]__0i0wtlu._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/lib_maintenance_repository_ts_10bkm28._.js")
R.c("server/chunks/lib_notifications_index_ts_0im0cs8._.js")
R.c("server/chunks/[root-of-the-server]__1_mkik-._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/lib_ai_assistant_conversations_ts_0gry3e6._.js")
R.c("server/chunks/lib_service-calls_index_ts_1pg5y58._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/1oeh_server_app_api_ai-operations_assistant_feedback_route_actions_19zwg24.js")
R.m(14615)
module.exports=R.m(14615).exports
