var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/approval-rules/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0i0wtlu._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/lib_maintenance_repository_ts_10bkm28._.js")
R.c("server/chunks/lib_notifications_index_ts_0im0cs8._.js")
R.c("server/chunks/[root-of-the-server]__13gpwkq._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/lib_approvals_0enn49i._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/_next-internal_server_app_api_approval-rules_[id]_route_actions_0-eu03b.js")
R.m(601747)
module.exports=R.m(601747).exports
