var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/audit/route.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__12-m4n9._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_audit_route_actions_1rkls8g.js")
R.m(287594)
module.exports=R.m(287594).exports
