var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/data-quality/settings/route.js")
R.c("server/chunks/[root-of-the-server]__1cy7qbz._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/[root-of-the-server]__0i0wtlu._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/_next-internal_server_app_api_data-quality_settings_route_actions_1wom6kd.js")
R.m(349867)
module.exports=R.m(349867).exports
