var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/system-logs/events/[id]/related/route.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/[root-of-the-server]__08f0j4w._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/1oeh_server_app_api_system-logs_events_[id]_related_route_actions_085_y-7.js")
R.m(780318)
module.exports=R.m(780318).exports
