var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/system-logs/security/[id]/dismiss/route.js")
R.c("server/chunks/[root-of-the-server]__0i0wtlu._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/[root-of-the-server]__1xgku4h._.js")
R.c("server/chunks/1oeh_server_app_api_system-logs_security_[id]_dismiss_route_actions_1prg8qb.js")
R.m(353401)
module.exports=R.m(353401).exports
