var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/pm/audit/route.js")
R.c("server/chunks/[root-of-the-server]__0wl_zl0._.js")
R.c("server/chunks/[root-of-the-server]__05y618u._.js")
R.c("server/chunks/lib_maintenance_pm-prisma-repository_ts_20kprft._.js")
R.c("server/chunks/lib_inventory_0b_k1uq._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/lib_maintenance_repository_ts_10bkm28._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_next-internal_server_app_api_pm_audit_route_actions_1p1h4k-.js")
R.m(38606)
module.exports=R.m(38606).exports
