var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/portal/settings/route.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/[root-of-the-server]__0emr8rm._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_next-internal_server_app_api_portal_settings_route_actions_0yyn2k6.js")
R.m(973395)
module.exports=R.m(973395).exports
