var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai-operations/predictive-maintenance/recommendations/route.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__0yp93p2._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/0ivl_api_ai-operations_predictive-maintenance_recommendations_route_actions_0yr2l72.js")
R.m(292163)
module.exports=R.m(292163).exports
