var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/executive-command-center/predictive-analytics/scenarios/route.js")
R.c("server/chunks/[root-of-the-server]__1gvceft._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/lib_crm_repository_ts_1qe6se3._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/lib_service-calls_index_ts_1pg5y58._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/lib_inventory_0b_k1uq._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/lib_service-dispatch_index_ts_0_wn224._.js")
R.c("server/chunks/[root-of-the-server]__1clsvjc._.js")
R.c("server/chunks/07_e_executive-command-center_predictive-analytics_scenarios_route_actions_0-ospc4.js")
R.m(860642)
module.exports=R.m(860642).exports
