var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai-operations/automations/templates/route.js")
R.c("server/chunks/[root-of-the-server]__0i0wtlu._.js")
R.c("server/chunks/lib_notifications_index_ts_0im0cs8._.js")
R.c("server/chunks/lib_automations_engine_execute-automation_ts_1rt4627._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/[root-of-the-server]__1ryg8d0._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/lib_maintenance_repository_ts_10bkm28._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/1oeh_server_app_api_ai-operations_automations_templates_route_actions_1t4f02o.js")
R.m(557700)
module.exports=R.m(557700).exports
