import type {
  CustomerLocationAccess,
  CustomerMembership,
  CustomerPrinterAccess,
  PortalAnnouncement,
  PortalDocument,
  PortalFeedback,
  PortalInvitation,
  PortalMessage,
  PortalNotificationPreference,
  SupportContactConfig,
} from "./types";

const now = "2026-07-11T12:00:00.000Z";

export const PORTAL_SUPPORT_CONTACT: SupportContactConfig = {
  teamName: "Matrix Service Desk",
  phone: "+1-555-0140",
  email: "service@matrix.example",
  emergencyPhone: "+1-555-0199",
  hours: "Mon–Fri 07:00–18:00 ET",
};

export const PORTAL_MEMBERSHIPS: CustomerMembership[] = [
  {
    id: "mem-sfx-admin",
    clerkUserId: "clerk_portal_admin_sfx",
    email: "admin@sfx-mpx.example",
    displayName: "SFX Portal Admin",
    customerId: "cust-sfx",
    role: "CUSTOMER_ADMIN",
    status: "ACTIVE",
    invitedBy: "Matrix Staff",
    invitedAt: "2026-01-10T10:00:00.000Z",
    acceptedAt: "2026-01-11T10:00:00.000Z",
    disabledAt: null,
    lastPortalLogin: now,
    canApproveService: true,
    canViewMeters: true,
    canViewPm: true,
    canDownloadReports: true,
    canManageUsers: true,
    jobTitle: "Facilities Director",
    phone: "555-1001",
    preferredContactMethod: "EMAIL",
    timeZone: "America/New_York",
    defaultLocationId: "site-sfx-main",
    createdAt: "2026-01-11T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "mem-sfx-manager",
    clerkUserId: "clerk_portal_mgr_sfx",
    email: "manager@sfx-mpx.example",
    displayName: "SFX Site Manager",
    customerId: "cust-sfx",
    role: "CUSTOMER_MANAGER",
    status: "ACTIVE",
    invitedBy: "SFX Portal Admin",
    invitedAt: "2026-02-01T10:00:00.000Z",
    acceptedAt: "2026-02-02T10:00:00.000Z",
    disabledAt: null,
    lastPortalLogin: now,
    canApproveService: true,
    canViewMeters: true,
    canViewPm: true,
    canDownloadReports: true,
    canManageUsers: false,
    jobTitle: "Print Ops Manager",
    phone: "555-1002",
    preferredContactMethod: "PHONE",
    timeZone: "America/New_York",
    defaultLocationId: "site-sfx-main",
    createdAt: "2026-02-02T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "mem-sfx-user",
    clerkUserId: "clerk_portal_user_sfx",
    email: "user@sfx-mpx.example",
    displayName: "SFX Operator",
    customerId: "cust-sfx",
    role: "CUSTOMER_USER",
    status: "ACTIVE",
    invitedBy: "SFX Portal Admin",
    invitedAt: "2026-03-01T10:00:00.000Z",
    acceptedAt: "2026-03-02T10:00:00.000Z",
    disabledAt: null,
    lastPortalLogin: now,
    canApproveService: false,
    canViewMeters: true,
    canViewPm: true,
    canDownloadReports: true,
    canManageUsers: false,
    jobTitle: "Press Operator",
    phone: "555-1003",
    preferredContactMethod: "EMAIL",
    timeZone: "America/New_York",
    defaultLocationId: "site-sfx-main",
    createdAt: "2026-03-02T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "mem-sfx-viewer",
    clerkUserId: "clerk_portal_viewer_sfx",
    email: "viewer@sfx-mpx.example",
    displayName: "SFX Read-Only",
    customerId: "cust-sfx",
    role: "CUSTOMER_VIEWER",
    status: "ACTIVE",
    invitedBy: "SFX Portal Admin",
    invitedAt: "2026-04-01T10:00:00.000Z",
    acceptedAt: "2026-04-02T10:00:00.000Z",
    disabledAt: null,
    lastPortalLogin: null,
    canApproveService: false,
    canViewMeters: false,
    canViewPm: true,
    canDownloadReports: true,
    canManageUsers: false,
    jobTitle: "Observer",
    phone: "",
    preferredContactMethod: "EMAIL",
    timeZone: "America/New_York",
    defaultLocationId: "site-sfx-main",
    createdAt: "2026-04-02T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "mem-north-admin",
    clerkUserId: "clerk_portal_admin_north",
    email: "admin@northstar.example",
    displayName: "Northstar Admin",
    customerId: "cust-northstar",
    role: "CUSTOMER_ADMIN",
    status: "ACTIVE",
    invitedBy: "Matrix Staff",
    invitedAt: "2026-05-01T10:00:00.000Z",
    acceptedAt: "2026-05-02T10:00:00.000Z",
    disabledAt: null,
    lastPortalLogin: now,
    canApproveService: true,
    canViewMeters: true,
    canViewPm: true,
    canDownloadReports: true,
    canManageUsers: true,
    jobTitle: "IT Manager",
    phone: "555-2001",
    preferredContactMethod: "EMAIL",
    timeZone: "America/New_York",
    defaultLocationId: "site-north",
    createdAt: "2026-05-02T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "mem-sfx-disabled",
    clerkUserId: "clerk_portal_disabled_sfx",
    email: "disabled@sfx-mpx.example",
    displayName: "Disabled User",
    customerId: "cust-sfx",
    role: "CUSTOMER_USER",
    status: "DISABLED",
    invitedBy: "SFX Portal Admin",
    invitedAt: "2026-01-01T10:00:00.000Z",
    acceptedAt: "2026-01-02T10:00:00.000Z",
    disabledAt: "2026-06-01T10:00:00.000Z",
    lastPortalLogin: null,
    canApproveService: false,
    canViewMeters: false,
    canViewPm: false,
    canDownloadReports: false,
    canManageUsers: false,
    jobTitle: "",
    phone: "",
    preferredContactMethod: "EMAIL",
    timeZone: "America/New_York",
    defaultLocationId: null,
    createdAt: "2026-01-02T10:00:00.000Z",
    updatedAt: "2026-06-01T10:00:00.000Z",
  },
];

export const PORTAL_LOCATION_ACCESS: CustomerLocationAccess[] = [
  {
    id: "pla-1",
    membershipId: "mem-sfx-manager",
    locationId: "site-sfx-main",
    accessLevel: "APPROVE",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pla-2",
    membershipId: "mem-sfx-user",
    locationId: "site-sfx-main",
    accessLevel: "WRITE",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pla-3",
    membershipId: "mem-sfx-viewer",
    locationId: "site-sfx-main",
    accessLevel: "READ",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pla-4",
    membershipId: "mem-north-admin",
    locationId: "site-north",
    accessLevel: "APPROVE",
    createdAt: now,
    updatedAt: now,
  },
];

export const PORTAL_PRINTER_ACCESS: CustomerPrinterAccess[] = [
  {
    id: "ppa-1",
    membershipId: "mem-sfx-manager",
    printerId: "asset-mx-gd-002",
    accessLevel: "APPROVE",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ppa-2",
    membershipId: "mem-sfx-manager",
    printerId: "asset-mx-gl-001",
    accessLevel: "APPROVE",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ppa-3",
    membershipId: "mem-sfx-user",
    printerId: "asset-mx-gd-002",
    accessLevel: "WRITE",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ppa-4",
    membershipId: "mem-sfx-viewer",
    printerId: "asset-mx-gd-002",
    accessLevel: "READ",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ppa-5",
    membershipId: "mem-north-admin",
    printerId: "asset-ns-val-001",
    accessLevel: "APPROVE",
    createdAt: now,
    updatedAt: now,
  },
];

export const PORTAL_INVITATIONS: PortalInvitation[] = [
  {
    id: "inv-pending-1",
    email: "newhire@sfx-mpx.example",
    displayName: "New Hire",
    customerId: "cust-sfx",
    role: "CUSTOMER_USER",
    status: "PENDING",
    invitedBy: "SFX Portal Admin",
    invitedAt: "2026-07-08T10:00:00.000Z",
    expiresAt: "2026-07-22T10:00:00.000Z",
    acceptedAt: null,
    cancelledAt: null,
    locationIds: ["site-sfx-main"],
    printerIds: ["asset-mx-gd-002"],
    canApproveService: false,
    canViewMeters: true,
    canViewPm: true,
    canDownloadReports: true,
    canManageUsers: false,
  },
];

export const PORTAL_ANNOUNCEMENTS: PortalAnnouncement[] = [
  {
    id: "ann-1",
    title: "Holiday service hours",
    message: "Matrix Service Desk will operate reduced hours July 4 weekend.",
    customerId: "cust-sfx",
    locationId: null,
    priority: "NORMAL",
    startDate: "2026-07-01T00:00:00.000Z",
    endDate: "2026-07-15T00:00:00.000Z",
    createdBy: "Matrix Staff",
    visible: true,
    acknowledgmentRequired: false,
    createdAt: "2026-06-20T10:00:00.000Z",
    updatedAt: now,
  },
  {
    id: "ann-2",
    title: "Main plant dock access",
    message: "Use bay 2 for service vans. Badge required after 17:00.",
    customerId: "cust-sfx",
    locationId: "site-sfx-main",
    priority: "HIGH",
    startDate: "2026-07-01T00:00:00.000Z",
    endDate: null,
    createdBy: "Matrix Staff",
    visible: true,
    acknowledgmentRequired: true,
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: now,
  },
];

export const PORTAL_DOCUMENTS: PortalDocument[] = [
  {
    id: "pdoc-1",
    title: "GD9630 Quick Start",
    description: "Operator quick guide",
    category: "Quick Guides",
    fileUrl: "/portal-docs/gd9630-quickstart.pdf",
    customerId: "cust-sfx",
    locationId: null,
    printerId: "asset-mx-gd-002",
    visibleToCustomer: true,
    uploadedBy: "Matrix Staff",
    uploadedAt: "2026-05-01T10:00:00.000Z",
    expirationDate: null,
    version: 2,
    active: true,
  },
  {
    id: "pdoc-2",
    title: "Site safety briefing",
    description: "Main plant visitor safety",
    category: "Safety Information",
    fileUrl: "/portal-docs/sfx-main-safety.pdf",
    customerId: "cust-sfx",
    locationId: "site-sfx-main",
    printerId: null,
    visibleToCustomer: true,
    uploadedBy: "Matrix Staff",
    uploadedAt: "2026-04-15T10:00:00.000Z",
    expirationDate: null,
    version: 1,
    active: true,
  },
  {
    id: "pdoc-internal",
    title: "Internal pricing sheet",
    description: "Must never appear in portal",
    category: "Policies",
    fileUrl: "/internal/pricing.pdf",
    customerId: "cust-sfx",
    locationId: null,
    printerId: null,
    visibleToCustomer: false,
    uploadedBy: "Matrix Staff",
    uploadedAt: "2026-01-01T10:00:00.000Z",
    expirationDate: null,
    version: 1,
    active: true,
  },
];

export const PORTAL_MESSAGES: PortalMessage[] = [
  {
    id: "pmsg-1",
    ticketId: "",
    membershipId: "mem-sfx-user",
    senderDisplayName: "SFX Operator",
    body: "Machine is down — please prioritize.",
    createdAt: "2026-07-10T11:00:00.000Z",
    visibleToCustomer: true,
    attachmentName: null,
    readByCustomer: true,
  },
];

export const PORTAL_FEEDBACK: PortalFeedback[] = [];

export function defaultNotificationPrefs(
  membershipId: string,
): PortalNotificationPreference {
  return {
    membershipId,
    ticketUpdates: "IMMEDIATE",
    appointments: "IMMEDIATE",
    pmUpdates: "DAILY",
    reports: "IMMEDIATE",
    announcements: "IMMEDIATE",
    inAppEnabled: true,
    emailEnabled: false,
    smsEnabled: false,
    updatedAt: now,
  };
}
