var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/pm/reports/route.js")
R.c("server/chunks/[root-of-the-server]__1gvceft._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/lib_maintenance_repository_ts_10bkm28._.js")
R.c("server/chunks/lib_maintenance_pm-prisma-repository_ts_20kprft._.js")
R.c("server/chunks/[root-of-the-server]__1jxco_b._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/lib_inventory_0b_k1uq._.js")
R.c("server/chunks/_next-internal_server_app_api_pm_reports_route_actions_2101r51.js")
R.m(277671)
module.exports=R.m(277671).exports
