var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai-operations/decisions/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0i0wtlu._.js")
R.c("server/chunks/lib_auth_permissions_ts_1qwthzt._.js")
R.c("server/chunks/lib_notifications_index_ts_0im0cs8._.js")
R.c("server/chunks/lib_decision-engine_0rzu5oy._.js")
R.c("server/chunks/lib_service-calls_index_ts_1pg5y58._.js")
R.c("server/chunks/lib_0a8lys6._.js")
R.c("server/chunks/[root-of-the-server]__202_lon._.js")
R.c("server/chunks/[root-of-the-server]__1r01cl_._.js")
R.c("server/chunks/lib_maintenance_repository_ts_10bkm28._.js")
R.c("server/chunks/node_modules_0t5_ff-._.js")
R.c("server/chunks/lib_inventory_0-vhprr._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__1v-08mk._.js")
R.c("server/chunks/_next-internal_server_app_api_ai-operations_decisions_[id]_route_actions_1x3ekcc.js")
R.m(935130)
module.exports=R.m(935130).exports
